### ISSUE TITLE
Template review feedback

### ISSUE THREAD

**Issue by praveena-pappu** [braze-inc/braze-gtm-initialization#1]
Thanks for submitting a template to the gallery, there were a few issues in your template that needed to be resolved ahead of approving the template for the gallery.

1) encodeUriComponent should be used on user provided values that are then used as parameters in your url. These methods take in a single text argument and return a URI Encoded string. You should use this method on "data.sdkVersion" when generating the url
const url = 'https://js.appboycdn.com/web-sdk/'+ data.sdkVersion +'/appboy.min.js';
2) The readme.md doesn't provide any information. Instead it redirects user to the gallery page which is irrelevant. Please provide valid information if any about the template.

**Comment by davidbielik** [comment]
Hi @praveena-pappu thanks for the prompt review! I've updated the repo with your requested changes.

**Comment by spvismaya** [comment]
Reopening temporarily to test an integration
