### ISSUE TITLE
Add "Enable Tracking" option

### ISSUE THREAD

**Issue by Minishlink** [braze-inc/braze-gtm-initialization#10]
Hello,

To be GDPR compliant, you would need to load the Braze SDK only after it has been consented. Take the following user flow:

* user goes to the page
* Braze is not loaded as per GDPR
* user accepts cookies
* Braze is loaded and Braze.initialize() is called through this GTM tag
* user then refuses cookies
* Braze.disableSDK() is called through the GTM action tag
* user reloads the page
* Braze is not loaded as per GDPR
* user then re-accepts cookies
* Braze.initialize() is called though this GTM tag but the user still has the "disable cookie" present, so Braze skips all activity

In this case, we would need to call enableSDK after Braze has been loaded, but before Braze.initialize()

You can probably workaround this by duplicating the initialization tag and user tag sequencing + the GTM action tag with enable SDK but that would open two sessions in a row, or maybe not, I don't know Braze internals and I don't really want to know.

I basically modified the template with

```js
  if (data.disableTracking) {
    const disableSdkName = majorVersion >= 4 ? 'disableSDK' : 'stopWebTracking';
    callInWindow(sdkObject + '.' + disableSdkName);
  } else {
    if (data.enableTracking) {
      const enableSdkName = majorVersion >= 4 ? 'enableSDK' : 'resumeWebTracking';
      callInWindow(sdkObject + '.' + enableSdkName);
    }

    // Initialize the SDK with api key and base url (from user input)
    callInWindow(sdkObject + '.initialize', data.apiKey, options);
```

This is not really an issue for 99% of the users, but for non technical people of a product team this can get confusing that it doesn't work

**Comment by davidbielik** [comment]
Hi @Minishlink, calling the disableSDK method on each page would unfortunately have some performance impact.

As an alternative, you can sequence the Action Tag set to Enable SDK prior to initialization if the user has opted in. 

If the user has opted out, then you can trigger the Action Tag set to Disable SDK and don't initialize the SDK.

Let me know if you see any issues with this approach.

**Comment by Minishlink** [comment]
Hello, we don't call disableSDK method on each page

By default we don't call the GTM initialization tag. So Braze is not loaded and not initialized.
If the user consents, the tag is called.
If the user refuses, we call disableSDK when he refuses - if he had not previously consented, nothing happens because Braze is not loaded; if he had previously consented, disableSDK disables the SDK and set the opt out cookie.

Now the problem is in the flow that I explained earlier: 
* user accepts
* user refuses
* now when the user loads a fresh page: the Braze SDK is not loaded and he has an opt out cookie
* if the user accepts again the cookies, then we have to load the Braze SDK, call enableSDK to clear the opt out cookie, followed by Braze.initialize

However, this is not possible with the current tag. The only possible way is to call the initialization tag (which loads Braze and call Braze.initialize()), and then call enableSDK, and then call again the initialization tag (because you need to call Braze.initialize() after enableSDK). Unfortunately, GTM is already not a very maintainable piece of software, so there's no way I'm adding this complicated logic (which might work in theory but in practice I'm quite sure it would take more time than needed for this problem)

So the best approach is to modify this template and add an enableSDK option (that could be called only if the SDK is disabled)

**Comment by davidbielik** [comment]
I believe you can accomplish the same thing using Tag Sequencing. For example, set the "Resume Tracking" action as a prerequisite for running the Initialization tag:

<img width="906" alt="image" src="https://github.com/braze-inc/braze-gtm-initialization/assets/7410770/8e4f0ebc-4a7c-4ef8-bc0a-893f66c230f2">

**Comment by Minishlink** [comment]
Please read my messages carefully, all the information is there.
You can't call resume tracking before initialization, because you need Braze loaded and that's through the initialization tag.
The simplest and most efficient way to circumvent this is to add the enable tracking option that calls enable SDK between loading and initialization
If you still don't see the problem, I think the best course of action would be for you to do the process of creating a blank app with Braze **while respecting GDPR** (this should have been done from the beginning), so with the following constraints:

* Braze is not loaded by default (GDPR is optin not optout)
* It is initialized and enabled on user consent
* It can be disabled after being enabled and initialized
* It can be enabled again and initialized after an optin followed by optout and a page refresh

**Comment by davidbielik** [comment]
Thanks @Minishlink I understand now. I'll check with our team and let you know what we can do.

**Comment by davidbielik** [comment]
Hi @Minishlink - thanks for creating this issue. The new "Re-enable Tracking" initialization option has been added. It should be available to upgrade once Google picks it up from github.

https://www.braze.com/docs/developer_guide/platform_integration_guides/web/google_tag_manager/#upgrading
